theme: minima

locale                   : "en-US"
title                    : ""
title_separator          : "-"
name                     : "Shazny Ramlan"
description              : "Susty law researcher and teacher."
