theme: minima

locale                   : "en-US"
title                    : "Shazny Ramlan"
title_separator          : "-"
name                     : "shazology"
description              : "Susty law researcher and teacher."
